import numpy as np

# Note: All docstrings were generated by Claude (Anthropic) Sonnet 3.7, April 2025

def gaussian_design(BT, samples_per_symbol, span, normalize=True):
    """
    Create a Gaussian filter for GMSK modulation with normalized frequency. Based on GSM spec (https://www.etsi.org/deliver/etsi_ts/100900_100999/100959/08.04.00_60/ts_100959v080400p.pdf)

    Note: This function was generated with assistance from Claude (Anthropic) Sonnet 3.7 & Google AI (Gemini 2.5 Pro), April 2025
    
    Parameters
    ----------
    BT : float
        Bandwidth-Time product (typically 0.3 for GMSK)
    samples_per_symbol : int
        Number of samples per symbol
    span : int
        Filter span in symbol periods
    normalize: bool
        Whether or not to normalize filter to unit energy. Default is True.
    
    Returns
    -------
    numpy.ndarray
        Gaussian filter coefficients
    """
    
    # Check if BT is positive
    if BT <= 0:
        raise ValueError("Error gaussian_design.py: Bandwidth time product must be positive")

    # Check if span is at least 1
    elif (span < 1):
        raise ValueError('Error gaussian_design.py: Span must be greater than or equal to 1')

    # Check if span is an integer 
    elif not isinstance(span, int):
        raise TypeError('Error gaussian_design.py: Span must be an integer')

    # Check if samples per symbol is greater than 1
    if (samples_per_symbol <= 1):
        raise ValueError('Error gaussian_design.py: Samples per symbol must be greater than 1')

    # Check if samples per symbol is an integer
    elif not isinstance(samples_per_symbol, int):
        raise TypeError('Error gaussian_design.py: Samples per symbol must be an integer')
    
    # Calculate filter length (in samples)
    filter_length = samples_per_symbol * span
    
    # Ensure filter length is odd
    if filter_length % 2 == 0:
        filter_length += 1
    
    # Time base centered at zero (normalized by symbol duration)
    t = np.arange(-(filter_length//2), filter_length//2 + 1) / samples_per_symbol

    T = samples_per_symbol
    
    # Standard deviation of the Gaussian pulse (normalized)
    sigma = np.sqrt(np.log(2)) / (2 * np.pi * BT)
    
    # Gaussian pulse (without PDF normalization factor)
    h = np.exp(-(t**2)/(2*sigma**2)) 

    if normalize:
        h = h/(np.sqrt(2*np.pi) * sigma * T)
    
    return np.convolve(h, np.ones(T)/T)

def rectangular_design(span, normalize=True):
    """
    Design a rectangular pulse shaping filter.
    
    Creates a rectangular (flat) filter impulse response with the specified span
    and normalized to unit energy.
    
    Parameters
    ----------
    span : int
        The number of samples in the rectangular filter
    normalize: bool
        Whether or not to normalize filter to unit energy. Default is True.
        
    Returns
    -------
    numpy.ndarray
        Normalized rectangular filter weights with unit energy
    """

    # Check if span is at least 1
    if (span < 1):
        raise ValueError('Error rectangular_design.py: Span must be greater than or equal to 1')

    # Check if span is an integer 
    elif not isinstance(span, int):
        raise TypeError('Error rectangular_design.py: Span must be an integer')
    
    weights = np.ones(span)

    if normalize:
        weights = weights/np.sum(weights)

    return weights


# Matt @ WaveWalkerDSP.com
# https://wavewalkerdsp.com
# Twitter: @WaveWalkerDSP
#
#
# Copyright 2021, Matt @ WaveWalkerDSP.com
#
# Permission is hereby granted, free of charge, to any person obtaining a copy 
# of this software and associated documentation files (the "Software"), to deal 
# in the Software without restriction, including without limitation the rights to 
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies 
# of the Software, and to permit persons to whom the Software is furnished to do 
# so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all 
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS 
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR 
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER 
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN 
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

def srrc_design ( SPS, span, beta, normalize=True):
    """
    Design a Square Root Raised Cosine (SRRC) pulse shaping filter.

    This function is created by Matt @ WaveWalkerDSP.com
    Indentation, comments, and normalization updated by Gemini (Google).

    Creates a Square Root Raised Cosine filter with the specified parameters.
    This filter is commonly used in digital communication systems for pulse
    shaping to minimize intersymbol interference.

    Parameters
    ----------
    SPS : int
        Samples per symbol (oversampling factor), must be an integer > 1
    span : int
        Filter span in symbols, must be an integer >= 1
    beta : float
        Roll-off factor (excess bandwidth), must be between 0 and 1
    normalize: bool
        Whether or not to normalize filter to unit energy. Default is True.

    Returns
    -------
    numpy.ndarray
        Filter coefficients of the SRRC filter normalized,
        or an empty list if input parameters are invalid
    """
    invalidParameter = False
    # Check if SPS is greater than 1
    if (SPS <= 1):
        raise ValueError('Error srrc_design.py: SPS must be greater than 1')
    # Check if SPS is an integer
    elif not isinstance(SPS, int):
        raise TypeError('Error srrc_design.py: SPS must be an integer')
    # Check if span is at least 1
    elif (span < 1):
        raise ValueError('Error srrc_design.py: span must be greater than or equal to 1')
    # Check if span is an integer
    elif not isinstance(span, int):
        raise TypeError('Error srrc_design.py: span must be an integer')
    # Check if beta is non-negative
    elif (beta < 0):
        raise ValueError('Error srrc_design.py: beta must be greater than or equal to 0')
    # Check if beta is less than or equal to 1 (implied by definition, but good practice)
    elif (beta > 1):
        raise ValueError('Error srrc_design.py: beta must be less than or equal to 1')
    # --- Filter Design ---
    # Check if any parameter was invalid
    if (invalidParameter):
        # Return empty filter weights if parameters are invalid
        return []
    else: # Parameters are valid, proceed with design
        # Build the time index array
        # // performs integer division
        nList = np.arange(-span*SPS//2, (span*SPS)//2 + 1)
        # Pre-allocate memory for weights for efficiency
        weights = np.zeros(len(nList))
        # Compute the weights on a sample-by-sample basis
        for index in range(len(nList)):
            # Select the current time index
            n = nList[index]
            t = n / SPS # Time in symbol periods
            # Apply the SRRC filter design equations
            # Handle the t=0 case (center tap)
            if (n == 0): # Equivalent to t == 0
                weights[index] = (1/np.sqrt(SPS)) * (1 - beta + (4 * beta / np.pi))
            # Handle the singularity points: t = +/- 1 / (4*beta)
            elif (np.abs(n * 4 * beta) == SPS): # Equivalent to np.abs(t) == 1 / (4*beta)
                term1 = (1 + (2 / np.pi)) * np.sin(np.pi / (4 * beta))
                term2 = (1 - (2 / np.pi)) * np.cos(np.pi / (4 * beta))
                weights[index] = (beta / np.sqrt(2 * SPS)) * (term1 + term2)
            # General case for other time indices
            else:
                numerator = np.sin(np.pi * n * (1 - beta) / SPS) + \
                            (4 * beta * n / SPS) * np.cos(np.pi * n * (1 + beta) / SPS)
                denominator = (np.pi * n / SPS) * (1 - (4 * beta * n / SPS)**2)
                weights[index] = (1 / np.sqrt(SPS)) * (numerator / denominator)
        # --- Normalization ---
        # Normalize the filter coefficients to have unit energy (sum of squares = 1)
        # This is the standard normalization for SRRC filters.
        # The original code scaled by 1/sqrt(SPS), which normalizes the sum, not energy.
        # if normalize:
        #     energy = np.sum(weights**2)
        #     if energy > 1e-10: # Avoid division by zero if weights are all zero
        #          weights = weights / np.sqrt(energy)
        # If you prefer the original normalization (0dB gain at f=0), uncomment the line below
        weights = weights / np.sqrt(SPS) # Original normalization
        return weights

def rc_design(samples_per_symbol, span, beta, normalize=True):
    # Check if span is at least 1
    if (span < 1):
        raise ValueError('Error gaussian_design.py: Span must be greater than or equal to 1')

    # Check if span is an integer 
    elif not isinstance(span, int):
        raise TypeError('Error gaussian_design.py: Span must be an integer')

    # Check if samples per symbol is greater than 1
    if (samples_per_symbol <= 1):
        raise ValueError('Error gaussian_design.py: Samples per symbol must be greater than 1')

    # Check if samples per symbol is an integer
    elif not isinstance(samples_per_symbol, int):
        raise TypeError('Error gaussian_design.py: Samples per symbol must be an integer')

    # Calculate filter length (in samples)
    filter_length = samples_per_symbol * span
    
    # Ensure filter length is odd
    if filter_length % 2 == 0:
        filter_length += 1

    # Create RC pulse shaping design by convolving SRRC pulse with itself
    h_srrc = srrc_design(samples_per_symbol, span, beta)
    h_rc = np.convolve(h_srrc, h_srrc, "same")
        
    return h_rc